<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Поддержка предоставления услуг телефонной связи</title>
    <link rel="stylesheet" type="text/css" href="style.css">
</head>
<body>
<?php require_once('ConnectDB.php'); ?>
<div id="page">
    <div id="header">
        <div id="nav">
            <div class="navItemDiv"><form><button type="submit" class="navItem" formaction="Analize.html">Анализ по предпочтениям</button></form></div>
            <div class="navItemDiv"><button class="navItem" data-modal-target="#modal">Учёт и фильтр &triangledown;</button></div>
            <div class="modal" id="modal">
                <ul>
                    <li><a href="Inserting.html">Добавление</a></li>
                    <li><a href="Deleting.html">Удаление</a></li>
                    <li><a href="Updating.html">Обновление</a></li>
                    <li><a href="Selecting.phtml">Просмотр</a></li>
                    <li><a href="Filtering.phtml">Фильтрация</a></li>
                </ul>
            </div>
            <div id="overlay"></div>
            <div class="navItemDiv"><form><button class="navItem" formaction="BillingConnect.html">Переход в биллинговую систему</button></form></div>
            <div class="navItemDiv"><form><button class="navItem" formaction="Reports.html">Создание отчётов</button></form></div>
        </div>
        <h1>Поддержка предоставления услуг телефонной связи</h1>
    </div>
    <div id="middle">
        <div id="add">
            <p>Просмотр данных в таблице</p>
            <p class="select_table">Выберите таблицу для просмотра данных:</p>
            <form method="post" action="Selecting.phtml">
                <select name="show_table" id="show_table">
                    <option value="Клиент">Клиент</option>
                    <option value="Название_тарифа">Название тарифа</option>
                    <option value="Оператор">Оператор</option>
                    <option value="Отчёты">Отчёты</option>
                    <option value="Планы">Планы</option>
                    <option value="Предоставление_услуг">Предоставление услуг</option>
                    <option value="Договор">Договор</option>
                    <option value="Должность">Должность</option>
                    <option value="Тариф">Тариф</option>
                    <option value="Сотрудник">Сотрудник</option>
                    <option value="Услуги_для_тарифа">Услуги для тарифа</option>
                    <option value="Услуги_оператора">Услуги оператора</option>
                    <option value="Услуга">Услуга</option>
                    <option value="Учёт_рабочего_времени">Учёт рабочего времени</option>
                    <option value="users">Пользователи</option>
                </select><br>
                <input type="submit" name="type[look_send]"  id="look_button" value="Отобразить данные из таблицы">
                <script src="Modals.js"></script>
                <meta charset="UTF-8">
                <?php require_once('Selecting.php'); ?>
            </form>
        </div>
    </div>
    <div id="footer">

    </div>
</div>

</body>
</html>